version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo_catdb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
